name: QuickQuill CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16  
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pgsql
        

    - name: Cache Composer Dependencies
      uses: actions/cache@v3
      with:
        path: server/vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-


    - name: Install Composer Dependencies
      run: |
        cd server
        composer install --prefer-dist --no-interaction --no-progress


    - name: Setup Laravel Environment Variables
      env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      run: |
        cd server
        cp .env.example .env

        echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" >> .env
        echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> .env


    - name: Run the Laravel Test
      run: |
        cd server
        php artisan test
